# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 201c80e0778d62a388c32f552f151ba2d6e6a3eb23f3496c6f44d03009ac8cb9eb1c45344cab71ca754faa0d6fe087720e50b2fa72b099fdfcd6f076b04601f0

test:
  secret_key_base: 7488df6764f97760e9705d27917955ed8a108bad482c4d11ccb93f2b5a770c00bbe4ddb3e47a6e8bbcdafb7fc09b6cb36794e5f2f4b645f45fdcf28962fe9d6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
